### PR TITLE
escaped hackers joke

### PR DESCRIPTION
**Pull request by tpage99**

### CODE REVIEW

**Comment by israelfloresdga** [comment]
Maybe is because i'm not a native english speaker, but someone can explain me the joke here? Please

**Comment by tpage99** [comment]
> Maybe is because i'm not a native english speaker, but someone can explain me the joke here? Please
> 
> Edit: I know the word ransom. That's it?

@israelfloresdga "ransomware" is a commonly used hacker method where a hacker takes someone's files/data and holds it "hostage" in exchange for a ransom. The response in this joke can be read as implied [he/they] "ran somewhere." As in they escaped because they ran somewhere.

**Comment by sw-yx** [comment]
this is pretty good!

**Comment by israelfloresdga** [comment]
... O-Oh! Nice
Thanks @tpage99

**Pull request merged**
