### PR TITLE
why is python like the USSR? no private fields

### PR DESCRIPTION
**Pull request by bennn**

### CODE REVIEW

**Comment by styfle** [comment]
This might be offensive 😐 

/cc @wesbos

**Comment by growlithe** [comment]
To whom?

**Comment by styfle** [comment]
Maybe I don't understand the joke. Can you explain?

**Comment by growlithe** [comment]
Sure, in early 1930s Stalin forcibly stripped landholders of their rights on land and built something called Kolkhoz (collective farms). More info here if you're curious https://en.wikipedia.org/wiki/Collectivization_in_the_Soviet_Union

This is actually a good one (well, as good as dad joke could be).

**Pull request merged**
