### PR TITLE
#LOL #TERRIFIC

### PR DESCRIPTION
**Pull request by joshmanders**
My life is spiraling out of control.

### CODE REVIEW

**Comment by styfle** [comment]
What is smurfing the web?

**Comment by chad3814** [comment]
> What is smurfing the web?

https://en.wikipedia.org/wiki/Smurf_attack

**Comment by joshmanders** [comment]
It's a play on words. In the 80's cartoon The Smurfs, all the Smurfs prefixed everything with `smurf` especially if it could rhyme with what they were saying. So if it was set in modern times, they wouldn't be "surfing the web" they'd be "smurfing the web"

**Comment by joshmanders** [comment]
Also Gargamel hated the Smurfs.

**Pull request merged**
