### PR TITLE
Jedi Joke

### PR DESCRIPTION
**Pull request by SwiftyProgrammer690**
I don't think anyone else has posted something like this

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Ouch 😅

We actually have a similar joke already:

> Why was the computer freezing?

**Comment by SwiftyProgrammer690** [comment]
What about the new one?

**Comment by SwiftyProgrammer690** [comment]
I just edited the file with

**Review by styfle — APPROVED** [review]
⭐

**Comment by SwiftyProgrammer690** [comment]
Nice!

**Pull request merged**
