### PR TITLE
Add a couple of jokes

### PR DESCRIPTION
**Pull request by alex-d-boyd**
Hope you like them :smile:

### CODE REVIEW

**Comment by styfle** [comment]
I don’t get it 🤔

**Comment by alex-d-boyd** [comment]
Well, they aren't going to be funny after I explain them, but here goes anyway:
Pieces of eight is another name for a Spanish dollar, a silver coin.
In treasure island, Long John Silver had a parrot that cried out "Pieces of eight", which has influenced the fictional depiction of pirates. (https://en.wikipedia.org/wiki/Spanish_dollar#Fiction)
A parity bit is an additional bit which is set based on the parity of the information bits, in order to provide simple error detection capabilities.  In an 8-bit byte, this leaves 7 bits for information, which covers all 7-bit (i.e. original) ASCII characters. (https://en.wikipedia.org/wiki/Parity_bit#Usage)
Errors detected by the parity bit are known as parity errors.
So a parrot sitting on a pirate's shoulder crying out "Pieces of seven" is suffering a 'parrot'y (parity) error.

And JS doesn't have classes, not enough class to get into the party :)

**Comment by styfle** [comment]
JS added classes years ago https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

**Comment by alex-d-boyd** [comment]
I stand corrected then.

**Pull request merged**
