### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by SwiftyProgrammer690**
Fixes https://github.com/wesbos/dad-jokes/issues/261

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
It should probably be license.md if you have markdown contents.

**Comment by SwiftyProgrammer690** [comment]
Fixed!

**Comment by SwiftyProgrammer690** [comment]
Yeah

**Comment by SwiftyProgrammer690** [comment]
Fixed that too

**Comment by SwiftyProgrammer690** [comment]
Yes

**Comment by SwiftyProgrammer690** [comment]
I think it is ready to be merged

**Comment by SwiftyProgrammer690** [comment]
cc meaning?

**Comment by SwiftyProgrammer690** [comment]
> Looks good to me 👍
> 
> cc @wesbos for further review

Sure thing!

**Comment by SwiftyProgrammer690** [comment]
I just did in gmail!

**Comment by SwiftyProgrammer690** [comment]
I will probably just close this because of inactivity...

**Comment by SwiftyProgrammer690** [comment]
this has been stale for a long time nowwwwww

**Pull request closed without merging**
